# be sure that your files are located in the same folder as this script
import re
import os

files = ["abbr.tex"]

folder_path = "to-be-merged/"
to_be_merged = []
if os.path.exists(folder_path) and os.path.isdir(folder_path):
    to_be_merged = [os.path.join(folder_path, f) for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]

files.extend(to_be_merged)

REGEX = r"^\\newacronym(\[(?P<plural>.*)\])?\{(?P<key>.*)\}\{(?P<abbr>.*)\}\{(?P<expand>.*)\}"

abbr = {}

for file_name in files:
    with open(file_name) as f:
       for line in f:
        line = line.strip()
        if not (len(line) == 0 or line.startswith("%")):
            m = re.search(REGEX, line)
            if m is not None:
                key = m.group('key')
                if key not in abbr:
                    abbr[key] = line
        
with open("abbr-sorted.tex", 'w') as f:
    f.write("% generated by Gilles Callebaut with the Github action: https://github.com/GillesC/action-abbreviations-latex\n\n")
    first_letter = ""
    for key in sorted(abbr, key=str.lower):
        if key[0] != first_letter:
            f.write(f"%%%%%%%%%%%% {key[0].upper()} %%%%%%%%%%%%\n")
            first_letter = key[0]
        f.write(f"{abbr[key]}\n")

