name: Merge and sort abbreviations
on: 
  push:
   paths:
      - 'abbr.tex' # only run when abbr. tex is changed
      - "to-be-merged/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      # - name: install python packages
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
          
      - name: Sort file
        run: |
          # Execute the Python script to modify the main.tex file
          python action.py

      - name: Move old to arxiv folder and update names
        run: |
          timestamp=$(date +'%Y%m%d%H%M%S')
          mkdir -p arxiv  # Create the 'arxiv' directory if it doesn't exist
          mv abbr.tex arxiv/abbr_${timestamp}.tex
          mv abbr-sorted.tex abbr.tex
          mv to-be-merged/* arxiv/
          
      - name: commit files
        run: |
          git pull --rebase
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "sorted abbreviations" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
